name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          cd frontend           # الدخول لفولدر الفرونت
          npm install           # تحميل المكتبات الخاصة بالفرونت
          npm run build         # إنشاء نسخة النشر

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  # تأكد لو اسم الفولدر build غيره هنا